export const productList = [
    {
        id: 1,
        category: "Gaming Mouse",
        name: "Logitech G703 Lightspeed",
        imageUrl: "https://m.media-amazon.com/images/I/719efVQ1tJL._AC_SY550_.jpg",
        price: "48.99",
    },
    {
        id: 2,
        category: "Gaming Mouse",
        name: "Logitech G305 Lightspeed",
        imageUrl: "https://m.media-amazon.com/images/I/61IiCJ7QggS._AC_SX466_.jpg",
        price: "46.99",
    },
    {
        id: 3,
        category: "Gaming Mouse",
        name: "Logitech G600 MMO",
        imageUrl: "https://m.media-amazon.com/images/I/81SvhwIiyAL._AC_SX679_.jpg",
        price: "39.99",
    },
    {
        id: 4,
        category: "Gaming Mouse",
        name: "Logitech G903 LIGHTSPEED",
        imageUrl: "https://m.media-amazon.com/images/I/61GTK3XJokL._AC_SX466_.jpg",
        price: "99.99",
    },
    {
        id: 5,
        category: "Gaming Mouse",
        name: "Logitech G604 LIGHTSPEED",
        imageUrl: "https://m.media-amazon.com/images/I/517H1HBj0kL._AC_SX466_.jpg",
        price: "61.99",
    },
    {
        id: 6,
        category: "Keyboard",
        name: "ANNE PRO 2",
        imageUrl: "https://m.media-amazon.com/images/I/61NrWLtBXFL._AC_SY450_.jpg",
        price: "79.99",
    },
    {
        id: 7,
        category: "Keyboard",
        name: "Cooler Master MK730",
        imageUrl: "https://m.media-amazon.com/images/I/61mdM0kzgjL._AC_SY355_.jpg",
        price: "112.99",
    },
    {
        id: 8,
        category: "Keyboard",
        name: "Logitech G PRO",
        imageUrl: "https://m.media-amazon.com/images/I/51K1mE5uVyL._AC_SY450_.jpg",
        price: "69.99",
    },
    {
        id: 9,
        category: "Keyboard",
        name: "Logitech G213 Prodigy",
        imageUrl: "https://m.media-amazon.com/images/I/61Nt8geXzWL._AC_SY355_.jpg",
        price: "38.95",
    },
    {
        id: 10,
        category: "Keyboard",
        name: "Logitech G910 Orion",
        imageUrl: "https://m.media-amazon.com/images/I/61IVHE8oy9L._AC_SY355_.jpg",
        price: "52.99",
    },
    {
        id: 11,
        category: "Gaming Headphones",
        name: "HyperX Cloud II",
        imageUrl: "https://m.media-amazon.com/images/I/71g5MRbP52L._AC_SY355_.jpg",
        price: "69.00",
    },
    {
        id: 12,
        category: "Gaming Headphones",
        name: "Razer Kraken X Ultralight",
        imageUrl: "https://m.media-amazon.com/images/I/61QIMDB3YTL._AC_SY355_.jpg",
        price: "29.99",
    },
    {
        id: 13,
        category: "Gaming Headphones",
        name: "Logitech G733",
        imageUrl: "https://m.media-amazon.com/images/I/71ub9aXwh0L._AC_SY355_.jpg",
        price: "149.99",
    },
    {
        id: 14,
        category: "Gaming Headphones",
        name: "Astro A10",
        imageUrl: "https://m.media-amazon.com/images/I/61o5JGe12OL._AC_SY355_.jpg",
        price: "71.39",
    },
    {
        id: 15,
        category: "Gaming Headphones",
        name: "SteelSeries Arctis 3",
        imageUrl: "https://m.media-amazon.com/images/I/71Xcl-j5ipL._AC_SY355_.jpg",
        price: "49.99",
    },
    {
        id: 16,
        category: "Gaming Monitor",
        name: "LG 27GL83A-B 27-Inch",
        imageUrl: "https://m.media-amazon.com/images/I/81dAe2wXIqL._AC_SX425_.jpg",
        price: "369.99",
    },
    {
        id: 17,
        category: "Gaming Monitor",
        name: "ASUS VP249QGR 23.8-Inch",
        imageUrl: "https://m.media-amazon.com/images/I/91G9etn8L4L._AC_SY355_.jpg",
        price: "179.99",
    },
    {
        id: 18,
        category: "Gaming Monitor",
        name: "SAMSUNG Odyssey G5 Series 27-Inch",
        imageUrl: "https://m.media-amazon.com/images/I/81cSdJuBbFL._AC_SX355_.jpg",
        price: "289.99",
    },
    {
        id: 19,
        category: "Gaming Monitor",
        name: "AOC CQ27G2 27-Inch",
        imageUrl: "https://m.media-amazon.com/images/I/81oORaahKZL._AC_SX355_.jpg",
        price: "239.99",
    },
    {
        id: 20,
        category: "Gaming Monitor",
        name: "ASUS TUF Gaming 32-Inch",
        imageUrl: "https://m.media-amazon.com/images/I/813VOQwrNtL._AC_SY355_.jpg",
        price: "299.99",
    },
];
